---
- name: lookup demo
  hosts: localhost
  tasks:
  - name: based on the ansible documentation about lookup plugin
    debug: msg="find the answer here:\n{{ lookup('url', 'https://google.com/search/?q=' + item|urlencode)|join(' ') }}"
    with_nested:
    - "{{ lookup('consul_kv', 'bcs/' + lookup('file', '/the/question') + ', host=localhost, port=2000')|shuffle}}"
    - "{{ lookup('sequence', 'end=42 start=2 step2')|map('log', 4)|list)}}"
    - ['a', 'c', 'd', 'c']
