---
- name: get vg sizes
  ignore_errors: yes
  hosts: ansible2,ansible3
  tasks:
  - name: covering ansible2
    block:
    - name: set vgroups sizes in variables
      set_fact:
        anssize: "{{ ansible_facts['lvm']['vgs']['vgfiles']['size_g'] | int }}" 
    - name: debug this
      debug:
        msg: the value of anssize is {{ anssize }}
    when:
    - ansible_hostname == "ansible2"
  - name: covering ansible3
    block:
    - name: show vgroups sizes
      set_fact:
        anssize: "{{ ansible_facts['lvm']['vgs']['vgfiles']['size_g'] | int }}"
    - name: debug this
      debug:
        msg: the value of anssize is {{ anssize }}
    when:
    - ansible_hostname == "ansible3"
